name: "Update Flake Deps"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  update-flake-deps:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Install nix
      uses: cachix/install-nix-action@v24
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Update flake deps
      run: nix flake update
    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore(deps): update flake deps"
        branch: master
